### ISSUE TITLE
Refactor method

### ISSUE THREAD

**Issue by PiotrGrzybowski** [szaudowsky/ai#2]
https://github.com/szaudowsky/ai/blob/8b4baa527390389d415dd4d5d94e64612012068d/individual.py#L32

How about:

`def parse_xml_file(path_to_xml):
return [Individual(child.get('duration'),
                          child.get('state'),
                          child.get('minDur'),
                          child.get('maxDur')) for child in et.parse(path_to_xml).getroot().iter('phase')]`

**Comment by szaudowsky** [comment]
fixed issue2.
